Repository Neighbook/Backend, pull requests merged in 2023-02, with the labels that each got.

#48 fix files upload and get file route
  src/api/controllers/filles_uploas_controller.ts
  src/api/routes/users/file_upload_routes.ts
  src/services/users_service/storage_service.ts
Labels: bug, backend

#51 [FIX]: Supression des infos sensible retourné par l'api user
  LICENCE
  src/api/controllers/user_controller.ts
  src/config/environnement.ts
  src/config/openapi.ts
  src/core/datastores/typeorm_datastores.ts
  src/dto/user/user_dto.ts
  src/middlewares/api/response_filter.ts
  src/middlewares/auth/auth_middleware.ts
  src/services/users_service/user_service.ts
Labels: bug

#52 fix reaction update
  src/api/routes/social/social_routes.ts
Labels: bug, enhancement

#53 fix reaction count and comment
  src/api/routes/social/social_routes.ts
  src/services/social/comment_service.ts
  src/services/social/post_service.ts
Labels: bug, enhancement

#54 add geolocalisation in events
  package.json
  src/api/routes/social/social_routes.ts
  src/core/utils/geolocalisation_utils.ts
  src/models/social/Coordonate.ts
  src/models/social/Evenement.ts
  src/models/social/GeoCodeObject.ts
  src/services/social/event_service.ts
Labels: backend, social

#57 add the feed for event (geolocated filter)
  src/api/routes/social/social_routes.ts
  src/services/social/post_service.ts
Labels: backend, social

#58 add adresse une bdd
  src/models/social/Evenement.ts
  src/services/social/event_service.ts
Labels: backend, social

#60 Nkr/fc/rt logic
  src/api/routes/social/social_routes.ts
  src/models/social/Post.ts
  src/services/social/post_service.ts
Labels: enhancement

#59 Fix create and get request for events
  src/services/social/event_service.ts
Labels: bug, backend, social
