Repository Neighbook/Backend, pull requests merged in 2023-01, with the labels that each got.

#11 Update readme based on new skeleton
  README.md
Labels: documentation

#12 [FONCTIONNALITÉ] : Ajout de la pipeline de génération de doc openapi
  .github/workflows/doc.yml
Labels: enhancement

#26 [Fonctionnalité]: Ajout du docker file et d'un docker-compose
  Dockerfile
  docker-compose.yml
  scripts/init_bd.sql
Labels: enhancement

#25 [Fonctionnalité]: Service de gestion des fichiers
  .gitignore
  Dockerfile
  README.md
  docker-compose.yml
  package.json
  scripts/sql/init_bd.sql
  src/api/controllers/filles_uploas_controller.ts
  src/api/routes/users/auth_routes.ts
  src/api/routes/users/file_upload_routes.ts
  src/app.ts
  src/config/environnement.ts
  src/config/openapi.ts
  src/core/azure/blob_storage_client.ts
  src/services/users_service/auth_service.ts
  src/services/users_service/storage_service.ts
  src/services/users_service/user_service.ts
  src/services/users_service/vault_service.ts
Labels: enhancement, backend

#30 [Fonctionnalité]: Ajout du support des base de donnée distante a notre api
  .gitignore
  src/config/api_config.ts
  src/config/environnement.ts
  src/core/datastores/typeorm_datastores.ts
Labels: backend

#34 [Fonctionnalité]: Ajouter des parametre a openapi
  src/config/openapi.ts
Labels: backend
